### ISSUE TITLE
brain-view2 can not open txt files with multiple columns

### ISSUE THREAD

**Issue by mcvaneede** [Mouse-Imaging-Centre/brain-view2#1]
brain-view2 was able to load an obj file and an associated text file with values for the vertices. With the upgrade to Ubuntu 12.04, this only seems possible with a single column of values. If you try to load a text file with multiple columns of values, brain-view2 "hangs".

**Comment by gdevenyi** [comment]
I found that it can open multi-column files if there's no headers, with headers, it hangs.

**Comment by gdevenyi** [comment]
Followup here, brain-view2 can open multi-column files in the mni.vertex.stats format https://github.com/BIC-MNI/mni.cortical.statistics/blob/master/R/vertex_glim.R#L754-L810

I believe this is also the format saved by ``vertstats_*`` tools from minc-toolkit

**Comment by mcvaneede** [comment]
Correct, the problem with this issues was not actually the multiple columns, but the presence of NA/Inf values.

**Comment by mcvaneede** [comment]
This is captured in issue #3, so closing this one.
